In [1]:
import sys
from sklearn.datasets import fetch_openml
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.neural_network import MLPClassifier  
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import cross_val_score

In [2]:
X, y = fetch_openml('mnist_784', version=1, return_X_y=True)
X = X.values
y = y.astype(int).values

print(X.shape)
print(y.shape)

(70000, 784)
(70000,)


In [3]:
X = ((X / 255.) - .5) * 2

In [ ]:
fig, ax = plt.subplots(nrows=2, ncols=5, sharex=True, sharey=True)
ax = ax.flatten()
for i in range(10):
    img = X[y == i][0].reshape(28, 28)
    ax[i].imshow(img, cmap='Greys')

ax[0].set_xticks([])
ax[0].set_yticks([])
plt.tight_layout()

plt.show()

In [4]:
X_temp, X_test, y_temp, y_test = train_test_split(
    X, y, test_size=10000, random_state=123, stratify=y)

X_train, X_valid, y_train, y_valid = train_test_split(
    X_temp, y_temp, test_size=5000, random_state=123, stratify=y_temp)

print(X_temp.shape)
print(y_temp.shape)

(60000, 784)
(60000,)


In [9]:
mlp = MLPClassifier(hidden_layer_sizes=(100,), random_state=42, )  
mlp.fit(X_train, y_train) 
y_pred = mlp.predict(X_test)


In [10]:
print(classification_report(y_test, y_pred))  
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       986
           1       0.99      0.99      0.99      1125
           2       0.98      0.97      0.98       999
           3       0.96      0.96      0.96      1020
           4       0.98      0.97      0.98       975
           5       0.96      0.96      0.96       902
           6       0.98      0.98      0.98       982
           7       0.97      0.97      0.97      1042
           8       0.96      0.97      0.96       975
           9       0.96      0.97      0.96       994

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000

[[ 966    0    1    1    2    1    5    4    4    2]
 [   0 1115    0    2    1    0    1    4    2    0]
 [   3    2  973    4    2    0    1    4    9    1]
 [   2    0    8  980    0   14    2    3    7    4]
 [   0    1    1    0  948   

In [11]:
scores = cross_val_score(estimator=mlp,
                         X=X_train,
                         y=y_train,
                         cv=10,
                         n_jobs=1)
print(f'CV accuracy scores: {scores}')
print(f'CV accuracy: {np.mean(scores):.3f} '
      f'+/- {np.std(scores):.3f}')

CV accuracy scores: [0.97690909 0.97709091 0.97727273 0.97527273 0.96745455 0.97436364
 0.97527273 0.97709091 0.96945455 0.97381818]
CV accuracy: 0.974 +/- 0.003
